
message_broker:
  sub_address: 'ipc://run/message_broker_sub'
  pub_address: 'ipc://run/message_broker_pub'

outer_server: # frontend
  location_handler_path: location
  client_location_handler_path: location
  db_nodes:
  - name: node_0
    db: 10
    host: localhost
    port: 6379
  - name: node_1
    db: 11
    host: localhost
    port: 6379
  - name: node_2
    db: 12
    host: localhost
    port: 6379
  - name: node_3
    db: 13,
    host: localhost
    port: 6379
  name_db:
    name: name_db
    db: 14
    host: localhost
    port: 6379


location_manager:
  pub_address: 'ipc://run/location_manager_pub'
  rep_address: 'ipc://run/location_manager_rep'
  pull_address: 'ipc://run/location_manager_pull'
  max_heartbeat_silence: 10 # seconds
  heartbeats_checker_period: 0.5 # seconds

location:
  heartbeat_period: 1 # seconds

