ident: main_location
pull_address: ipc://run/main_location_pull
pub_address: ipc://run/main_location_pub
db:
  name: main_location #same as an ident
  db: 15
  host: localhost
  port: 6379
work_handlers:
  path: configs/work_handlers.yaml
  tick_processors: 10
  works_per_step: 10

  
